UNIT EveLib;

INTERFACE

	FUNCTION EVEReset : INTEGER ;
	FUNCTION EVEStatus : INTEGER ;
	FUNCTION EVEEnable(VAR PASSWORD:STRING) : INTEGER ;
	FUNCTION EVEReadCTR : INTEGER ;
	FUNCTION EVEChallenge(LOCK,VALUE : INTEGER) : INTEGER ;
	FUNCTION EVEReadGPR(GPR : INTEGER) : INTEGER;
	FUNCTION EVEWriteGPR(GPR,VALUE : INTEGER) : INTEGER ;
	FUNCTION EVESetLock(LOCK,CHALLANGE,RESPONSE:INTEGER) : INTEGER ;

IMPLEMENTATION

	FUNCTION EVEReset : INTEGER ; EXTERNAL ;
	FUNCTION EVEStatus : INTEGER ; EXTERNAL ;
	FUNCTION EVEEnable(VAR PASSWORD:STRING) : INTEGER ; EXTERNAL;
	FUNCTION EVEReadCTR : INTEGER ; EXTERNAL ;
	FUNCTION EVEChallenge(LOCK,VALUE : INTEGER) : INTEGER ; EXTERNAL ;
	FUNCTION EVEReadGPR(GPR : INTEGER) : INTEGER; EXTERNAL ;
	FUNCTION EVEWriteGPR(GPR,VALUE : INTEGER) : INTEGER ; EXTERNAL ;
	FUNCTION EVESetLock(LOCK,CHALLANGE,RESPONSE:INTEGER) : INTEGER ; EXTERNAL ;

END.
